### ISSUE TITLE
IDEA: Add RPI-type to Version Info

### ISSUE THREAD

**Issue by RSlegers** [XavierBerger/RPi-Monitor-deb#10]
Is it possible to add the type of RPI to the Version info on the Status page?

Here's is a (incomplete) list of the version-numbers and how to get them:

Identifying Your Board Once Booted
 
Maybe you've got a Raspberry Pi in service, and you just can't remember what model it was and you really don't want to have to pull it out to look at its PCB. If you already have your Raspberry Pi running, you can find out the model of your Raspberry Pi by going to the terminal and issuing cat /proc/cpuinfo and looking up the last four digits in the table here. This will tell you which board, board revision, RAM and manufacturer all in one fell swoop. A summary of the table, grouped by model, is as follows:
Raspberry Pi Model A: 0007, 0008, 0009
Raspberry Pi Model B (Rev 1.0, 256Mb): 0002, 0003
Raspberry Pi Model B (Rev 2.0, 256Mb): 0004, 0005, 0006
Raspberry Pi Model B (Rev 2.0, 512Mb): 000d, 000e, 000f
Raspberry Pi Model A+: 0012
Raspberry Pi Model B+: 0010, 0013
Raspberry Pi 2 Model B: 1041

On a RPI 2B of mine it show the following text: "Revision        : a01041" On the for-last line.

**Comment by XavierBerger** [comment]
This issue would be better ins **RPi-Monitor** program repository than in **RPi-Monitor** package repository.

Anyway, the idea is not so bad. We could imagine a configuration template that could be activated and which will gather such information. If you have the opportunity to write such a configuration file, you can propose a pull request in **RPi-Monitor** _program repository_ into the _devel branch_. 

I'll keep this idea in mind and close this issue which is not in the right repository.
