### ISSUE TITLE
No "Release" for 2.11?

### ISSUE THREAD

**Issue by srcshelton** [XavierBerger/RPi-Monitor-deb#11]
https://github.com/XavierBerger/RPi-Monitor-deb/releases still shows 2.10 as the most recent release?

**Comment by srcshelton** [comment]
(I think the appropriate commit just needs to be tagged as 'v2.11'...)

**Comment by XavierBerger** [comment]
I'm working on the release of v2.11. This version is not yet officially available but it shouldn't take long.
I'll tag this repository I'll publicly release this version and publish an announcement post on my blog.

**Comment by srcshelton** [comment]
Ah - no worries: I assumed that the RPi-Monitor repo and this would be updated in lock-step, sorry ;)
