### ISSUE TITLE
wget rpimonitor.list

### ISSUE THREAD

**Issue by romainlouvet** [XavierBerger/RPi-Monitor-deb#12]
sudo wget http://goo.gl/rsel0F -> 404: Not Found

**Comment by XavierBerger** [comment]
V2.11 will be published soon with a new repository.
This will be fixed soon.

**Comment by SemihY** [comment]
sudo wget http://goo.gl/vewCLL -O /etc/apt/sources.list.d/rpimonitor.list

try this.
