### ISSUE TITLE
Display issue at upgradable Packages after upgrade

### ISSUE THREAD

**Issue by Woersty** [XavierBerger/RPi-Monitor-deb#14]
Hi Xavier,

we use your great tool as Plugin for our LoxBerry Project.

One of the [users](https://github.com/scharrin2) reported an display [issue](https://github.com/Woersty/LoxBerry-Plugin-RPi-Monitor/issues/3#issuecomment-248349153).

After an upgrade of the package the Package(s) section shows **0 upgradable(s)**
but the tooltip still displays a list.

See https://cloud.githubusercontent.com/assets/22325491/18678684/217ecbd4-7f5d-11e6-80ed-64d7cc309eb5.png

Can you have a look?

Regards 
Wörsty

**Comment by XavierBerger** [comment]
Bug described into RPi-Monitor repository. (Here we are in the package...)

**Comment by Woersty** [comment]
You are right, duplicate of https://github.com/XavierBerger/RPi-Monitor/issues/118 :grinning: 
Thanks.
