### ISSUE TITLE
showing required packages using apt instead of aptitude

### ISSUE THREAD

**Issue by wsirhc** [XavierBerger/RPi-Monitor-deb#16]
due to some problems using aptitude and apt parallely on armbian, I did a quick and dirty change to "/usr/share/rpimonitor/scripts/updatePackagesStatus.pl".
This worked for me to show count and names of packages ready to upgrade (see attachment).

I'd suggest to  
1.: add apt as third choise next to aptitude and checkupdates.
2.: make aptitude package not required as dependencie

cheers

[updatePackagesStatus.pl.txt](https://github.com/XavierBerger/RPi-Monitor-deb/files/1129008/updatePackagesStatus.pl.txt)

**Comment by XavierBerger** [comment]
Attachement is not working. Can you propose a pull request on RPi-Monitor directly (on devel branch) and not in the packaging project (here)?
I'm closing this issue.
