### ISSUE TITLE
Starting RPi-Monitor:Illegal instruction

### ISSUE THREAD

**Issue by sruckh** [XavierBerger/RPi-Monitor-deb#17]
Was running rpimonitor 2.11-r5 without any problem.  I assume a recent OS update has caused rpimonitor to stop working.  Only these lines are present when starting via 'sudo systemctl start rpimonitor':

Aug 25 13:26:33 xxxx systemd[1]: Starting LSB: RPi-Monitor daemon...
Aug 25 13:26:33 xxxx rpimonitor[22288]: Starting RPi-Monitor:Illegal instruction
Aug 25 13:26:33 xxxx rpimonitor[22288]: failed!
Aug 25 13:26:33 xxxx systemd[1]: Started LSB: RPi-Monitor daemon

This is with a raspberry pi3 running debian/Jessie (4.9.41-v7+) with all latest updates installed.  rpimonitor was installed using apt by adding the following source:

deb http://giteduberger.fr rpimonitor/

**Comment by XavierBerger** [comment]
I don't understand this error. By default, **RPi-Monitor** startup script is in sysVinit format.
Some users of **RPi-Monitor** did provide some script for systemd. You may check that in program repository.
In another hand, I just published v2.12... You can give a try and check but I didn't modifiy startup script.
