### ISSUE TITLE
"replace master by devel into the upper line" => but there is no "master" in upper line

### ISSUE THREAD

**Issue by jnachtigall** [XavierBerger/RPi-Monitor-deb#21]
The [README](https://github.com/XavierBerger/RPi-Monitor-deb/blob/master/README.md#repository) says:
> Note: To test unstable version, replace master by devel into the upper line.

I do not know what this is referring to, because in the upper line (`deb http://giteduberger.fr rpimonitor/`) there is no `master`. I guess this is something that has there been before and was forgotten to remove.

Just fyi, I do not use `unstable` but I guess you might want to fix this inconsistency.

**Comment by XavierBerger** [comment]
Fixed. Thanks for the feedback
