### ISSUE TITLE
Can't add key

### ISSUE THREAD

**Issue by NLstn** [XavierBerger/RPi-Monitor-deb#22]
Hi, 

I get the following error when adding your public key:
![image](https://user-images.githubusercontent.com/9517868/36743777-638ef46e-1beb-11e8-9c3b-7af2805cb4d1.png).

Can you tell me what the issue is?
Thanks!

**Comment by XavierBerger** [comment]
gpg: failed to start the dirmngr '/usr/bin/difmngr': No such file or directory.
Install dirmngr : `sudo apt-get install dirmngr` and try again.

Note: README.md updated.
