### ISSUE TITLE
Repository no longer works

### ISSUE THREAD

**Issue by egrueda** [XavierBerger/RPi-Monitor-deb#23]
Using repo as README.md shows, apt-get fails with error:
`E: The repository 'http://giteduberger.fr rpimonitor/ Release' does no longer have a Release file.`

Not sure if this software is still alive :-(

**Comment by EricSalemi** [comment]
I notified the website owner.

No answer yet.

**Comment by Leepic** [comment]
The repo works now. The file [Release](http://giteduberger.fr/rpimonitor/Release) is reachable.
Can you confirm?

**Comment by XavierBerger** [comment]
This was a web site side effect. Everything is back to the normal. Closing.
