### ISSUE TITLE
Transport RRD data from old installation to new one

### ISSUE THREAD

**Issue by Htaborda** [XavierBerger/RPi-Monitor-deb#7]
I had to reinstall a new instance of my RPi because of the switch from Raspbian Wheezy to Raspbian Jessie.

How do I carry over all the data I gathered in the last 2 years to the new instance? There should be some RRD or database files that I can copy from the old card....

**Comment by christian-0s** [comment]
Try looking in /var/lib/rpimonitor/stat

**Comment by XavierBerger** [comment]
Confirmed: RRD are stored into `/var/lib/rpimonitor/stat`
Copying them from previous installation will achieve you goal.
